
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network  

  backend:
      build: ./backend
      container_name: backend
      volumes:
      - ./backend/src:/app/src
      - /app/node_modules
      ports:
        - "6002:5000"
      environment:
        - MONGO_URI=mongodb://mongo:27017/todo-app
      depends_on:
         - mongo
      networks:
      - app-network
  frontend:
      build: ./frontend
       
      container_name: frontend
      volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public  # If using React
      - /app/node_modules
      ports:
         - "3001:3000"
      environment:
      - REACT_APP_API_URL=http://backend:5000   
      depends_on:
         - backend 
      networks:
      - app-network     
      

volumes:
   mongo-data:        

networks:
  app-network:
    driver: bridge

